### ISSUE TITLE
Can't add exp claims

### ISSUE THREAD

**Issue by AzSiAz** [googleapis/nodejs-iam-credentials#120]
1) Is this a client library issue or a product issue?
Client library

2) Did someone already solve this?
Not found

3) Do you have a support contract?
No

#### Environment details

  - OS: Linux
  - Node.js version: 16.14.0
  - npm version: -
  - `@google-cloud/iam-credentials` version: 1.1.1

#### Steps to reproduce
Generating a token like this
```ts
const { '0': iamData } = await this.#iamClient.signJwt({
    name: `projects/-/serviceAccounts/${this.#getServiceAccount()}`,
    payload: JSON.stringify({
        aud: `vault/${this.#role}`,
        sub: this.#getServiceAccount(),
        // exp: 3600,
    }),
})
```
Work fine, but as soon as I want to add an `exp` claim this package throw an error
```
error Error: 3 INVALID_ARGUMENT: Request contains an invalid argument.
    at Object.callErrorFromStatus (/dev-monorepo/node_modules/.pnpm/@grpc+grpc-js@1.5.9/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/dev-monorepo/node_modules/.pnpm/@grpc+grpc-js@1.5.9/node_modules/@grpc/grpc-js/src/client.ts:343:36)
    at Object.onReceiveStatus (/dev-monorepo/node_modules/.pnpm/@grpc+grpc-js@1.5.9/node_modules/@grpc/grpc-js/src/client-interceptors.ts:462:34)
    at Object.onReceiveStatus (/dev-monorepo/node_modules/.pnpm/@grpc+grpc-js@1.5.9/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at /dev-monorepo/node_modules/.pnpm/@grpc+grpc-js@1.5.9/node_modules/@grpc/grpc-js/src/call-stream.ts:330:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 3,
  details: 'Request contains an invalid argument.',
  metadata: Metadata {
    internalRepr: Map(1) { 'grpc-server-stats-bin' => [Array] },
    options: {}
  },
  note: 'Exception occurred in retry method that was not classified as transient'
}
```
Unfortunately I need an exp clain for vault to work correctly with this token (cf https://www.vaultproject.io/docs/auth/gcp#curl-example), but maybe there is another way to get an exp claim I am not seeing in TS types ? 

Thanks

**Comment by AzSiAz** [comment]
Seem like I misunderstood how exp work, closing
